In [5]:
# import pandas as pd

# # Read the gzipped CSV file
# df = pd.read_csv('../data/2019-Oct.csv.gz', compression='gzip', nrows=1_000_000)

# # Display the first few rows
# df.head()

In [6]:
# df.info()

In [7]:
# # Save to parquet format
# output_path = '../data/sample.parquet'
# df.to_parquet(output_path, compression='snappy')

## Load the data

In [1]:
import pandas as pd

# Verify the parquet file
output_path = '../data/sample.parquet'
df_parquet = pd.read_parquet(output_path)
print(f"Number of rows in parquet file: {len(df_parquet)}")

Number of rows in parquet file: 1000000

In [2]:
df_parquet[:20].to_csv('../data/sample.csv', index=False)

In [5]:
df_parquet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   event_time     1000000 non-null  object
 1   event_type     1000000 non-null  object
 2   product_id     1000000 non-null  int64
 3   category_id    1000000 non-null  int64
 4   category_code  681869 non-null   object
 5   brand          852440 non-null   object
 6   price          1000000 non-null  float64
 7   user_id        1000000 non-null  int64
 8   user_session   1000000 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 68.7+ MB

In [7]:
# Check null values in the event_time column
df_parquet['event_time'].isnull().sum()

0

In [9]:
df_parquet.head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,None,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,None,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d
5,2019-10-01 00:00:05 UTC,view,1480613,2053013561092866779,computers.desktop,pulser,908.62,512742880,0d0d91c2-c9c2-4e81-90a5-86594dec0db9
6,2019-10-01 00:00:08 UTC,view,17300353,2053013553853497655,None,creed,380.96,555447699,4fe811e9-91de-46da-90c3-bbd87ed3a65d
7,2019-10-01 00:00:08 UTC,view,31500053,2053013558031024687,None,luminarc,41.16,550978835,6280d577-25c8-4147-99a7-abc6048498d6
8,2019-10-01 00:00:10 UTC,view,28719074,2053013565480109009,apparel.shoes.keds,baden,102.71,520571932,ac1cd4e5-a3ce-4224-a2d7-ff660a105880
9,2019-10-01 00:00:11 UTC,view,1004545,2053013555631882655,electronics.smartphone,huawei,566.01,537918940,406c46ed-90a4-4787-a43b-59a410c1a5fb
10,2019-10-01 00:00:11 UTC,view,2900536,2053013554776244595,appliances.kitchen.microwave,elenberg,51.46,555158050,b5bdd0b3-4ca2-4c55-939e-9ce44bb50abd
11,2019-10-01 00:00:11 UTC,view,1005011,2053013555631882655,electronics.smartphone,samsung,900.64,530282093,50a293fb-5940-41b2-baf3-17af0e812101
12,2019-10-01 00:00:13 UTC,view,3900746,2053013552326770905,appliances.environment.water_heater,haier,102.38,555444559,98b88fa0-d8fa-4b9d-8a71-3dd403afab85
13,2019-10-01 00:00:15 UTC,view,44600062,2103807459595387724,None,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
14,2019-10-01 00:00:16 UTC,view,13500240,2053013557099889147,furniture.bedroom.bed,brw,93.18,555446365,7f0062d8-ead0-4e0a-96f6-43a0b79a2fc4
15,2019-10-01 00:00:17 UTC,view,23100006,2053013561638126333,None,None,357.79,513642368,17566c27-0a8f-4506-9f30-c6a2ccbf583b
16,2019-10-01 00:00:18 UTC,view,1801995,2053013554415534427,electronics.video.tv,haier,193.03,537192226,e3151795-c355-4efa-acf6-e1fe1bebeee5
17,2019-10-01 00:00:18 UTC,view,10900029,2053013555069845885,appliances.kitchen.mixer,bosch,58.95,519528062,901b9e3c-3f8f-4147-a442-c25d5c5ed332
18,2019-10-01 00:00:19 UTC,view,1306631,2053013558920217191,computers.notebook,hp,580.89,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
19,2019-10-01 00:00:19 UTC,view,1005135,2053013555631882655,electronics.smartphone,apple,1747.79,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d